name: ci

on:
  push:
    branches:
      - '**'

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  install-depencencies:
    uses: ./.github/workflows/__install-dependencies.yml

  lint:
    needs: install-depencencies
    uses: ./.github/workflows/__lint.yml

  builds:
    needs: install-depencencies
    uses: ./.github/workflows/__build.yml
